AWSTemplateFormatVersion: '2010-09-09'
Description: Hello Lambda + API Gateway v2 (HTTP API) example

Parameters:
  StageName:
    Type: String
    Default: prod

Resources:
  HelloLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  HelloFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: hello-cfn-function
      Handler: index.handler
      Runtime: nodejs18.x
      Role: !GetAtt HelloLambdaRole.Arn
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            const body = { message: "Hello, World!", ts: new Date().toISOString(), eventSummary: { method: event.requestContext?.http?.method, path: event.requestContext?.http?.path } };
            return { statusCode: 200, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) };
          };

  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: HelloHttpApi
      ProtocolType: HTTP

  LambdaIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloFunction.Arn}/invocations
      PayloadFormatVersion: "2.0"

  HelloRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "ANY /hello"
      Target: !Sub "integrations/${LambdaIntegration}"

  DeployStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: !Ref StageName
      AutoDeploy: true

  PermissionForApiToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref HelloFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*/*/hello"

Outputs:
  ApiEndpoint:
    Description: "HTTP API endpoint"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/hello"
